#ifndef CEL_PP_PARSE_H
#define CEL_PP_PARSE_H

#include "core.h"

typedef enum {
	CEL_PP_PARSE_FAIL = 0,
	CEL_PP_PARSE_END_OF_LINE,
	CEL_PP_PARSE_WHITESPACE,
	CEL_PP_PARSE_IDENTIFIER,
	CEL_PP_PARSE_PP_NUMBER,
	CEL_PP_PARSE_CHARACTER_CONSTANT,
	CEL_PP_PARSE_STRING_LITERAL,
	CEL_PP_PARSE_PUNCTUATOR,
	CEL_PP_PARSE_OTHER_CHAR,

	CEL_PP_PARSE_INCLUDE_HEADER_NAME,
	CEL_PP_PARSE_INCLUDE_HEADER_EXPAND,
	CEL_PP_PARSE_DEFINE_MACRO_OBJ,
	CEL_PP_PARSE_DEFINE_MACRO_FN,
	CEL_PP_PARSE_UNDEF,
	CEL_PP_PARSE_IFDEF,
	CEL_PP_PARSE_IFNDEF,
} cel_pp_parse_type;

typedef struct {
	const cel_char *start;
	const cel_char *end;
} cel_pp_parse_span;

#endif
